# Generated by Django 3.2.9 on 2021-11-15 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_ossio_queenslandservice_osssio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='australiancapitalterritoryservice',
            name='state',
        ),
        migrations.RemoveField(
            model_name='newsouthwalesservice',
            name='state',
        ),
        migrations.RemoveField(
            model_name='northernterritoryservice',
            name='state',
        ),
        migrations.RemoveField(
            model_name='queenslandservice',
            name='state',
        ),
        migrations.RemoveField(
            model_name='southaustraliaservice',
            name='state',
        ),
        migrations.RemoveField(
            model_name='tasmaniaservice',
            name='state',
        ),
        migrations.RemoveField(
            model_name='victoriaservice',
            name='state',
        ),
        migrations.RemoveField(
            model_name='westernaustraliaservice',
            name='state',
        ),
        migrations.AddField(
            model_name='stateservice',
            name='state',
            field=models.CharField(choices=[('ACT', 'Australian Capital Territory'), ('NSW', 'New South Wales'), ('NT', 'Northern Territory'), ('QLD', 'Queensland'), ('SA', 'South Australia'), ('TAS', 'Tasmania'), ('VIC', 'Victoria'), ('WA', 'Western Australia')], default=None, max_length=3),
        ),
    ]
