# Generated by Django 3.2.9 on 2021-11-15 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20211115_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='url',
            field=models.URLField(),
        ),
    ]
