# Generated by Django 3.2.9 on 2021-11-15 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_service_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
    ]
