# Generated by Django 3.2.9 on 2021-11-04 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='govconnectuser',
            name='address',
            field=models.CharField(max_length=150),
        ),
    ]
