# Generated by Django 3.2.9 on 2021-11-04 03:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_govconnectuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='govconnectuser',
            name='last_login',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
