# Generated by Django 3.2.9 on 2021-11-16 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_enabledservices_services'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AddField(
            model_name='govconnectuser',
            name='one_time_generator',
            field=models.BooleanField(default=False),
        ),
    ]
