# Generated by Django 3.2.9 on 2021-11-04 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_govconnectuser_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='govconnectuser',
            name='password',
        ),
    ]
