# Generated by Django 3.2.9 on 2021-11-13 07:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_govconnectuser_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='govconnectuser',
            old_name='address',
            new_name='state',
        ),
        migrations.AddField(
            model_name='govconnectuser',
            name='postcode',
            field=models.CharField(default=4000, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='govconnectuser',
            name='street_address',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='govconnectuser',
            name='suburb',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
