# Generated by Django 3.2.9 on 2021-11-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211113_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='govconnectuser',
            name='address',
            field=models.CharField(default='<django.db.models.fields.CharField>, <django.db.models.fields.CharField> <django.db.models.fields.CharField> <django.db.models.fields.CharField>', max_length=150),
        ),
        migrations.AlterField(
            model_name='govconnectuser',
            name='state',
            field=models.CharField(choices=[('QLD', 'Queensland'), ('VIC', 'Victoria'), ('TAS', 'Tasmania'), ('NSW', 'New South Wales'), ('NT', 'North Territory'), ('ACT', 'Australian Capital Territory'), ('WA', 'Western Australia'), ('SA', 'Southern Australia')], max_length=3),
        ),
    ]
