# Generated by Django 3.2.9 on 2021-11-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20211113_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='govconnectuser',
            name='address',
            field=models.CharField(max_length=150),
        ),
    ]
