# Generated by Django 3.2.9 on 2021-11-14 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_govconnectuser_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='govconnectuser',
            name='connected_services',
        ),
        migrations.CreateModel(
            name='EnabledServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
